### ISSUE TITLE
Elasticsearch fails if the "mappings/doc" section is empty in index shape

### ISSUE THREAD

**Issue by agazzarini** [SeaseLtd/rated-ranking-evaluator#69]
**Describe the bug**
The Elasticsearch binding is looking for a proper configured "doc" type under the "mappings" section of the index shape. If for somewhat reason you have an index shape without that section the data loading fails. 

**To Reproduce**
1. Use an index-shape.json without the "mappings" section or without a "doc" type. 
2. Starts the evaluation process
3. See error below

```
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.sease:rre-maven-elasticsearch-plugin:6.3.2:evaluate (search-quality-evaluation) on project rre-fosdem-walkthrough: Execution search-quality-evaluation of goal io.sease:rre-maven-elasticsearch-plugin:6.3.2:evaluate failed: MapperParsingException[Failed to parse mapping [doc]: malformed mapping no root object found]; nested: MapperParsingException[malformed mapping no root object found]; -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

MapperParsingException[Failed to parse mapping [doc]: malformed mapping no root object found]; nested: MapperParsingException[malformed mapping no root object found];
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:352)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:280)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$IndexCreationTask.execute(MetaDataCreateIndexService.java:443)
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45)
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:630)
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:267)
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:197)
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:132)
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:626)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
**Expected behavior**
The evaluation process should work even if the configuration doesn't specify a mappings/doc

**Comment by agazzarini** [comment]
Workaround until the issue is fixed: use an empty section like this: 
```
{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 0
  },
  "mappings": {
    "doc": {
      
    }
  }
}
```

**Comment by agazzarini** [comment]
Closing the issue because at the moment the workaround (the empty section posted above) works well.
